name: Build and deploy Angular app to Azure Web App - chatboxonline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use Ubuntu instead of Windows for consistency with logs
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies and build
      working-directory: /home/runner/work/ecommerce-app/ecommerce-app
      run: |
        npm install
        npm run build:prod

    - name: Verify build output
      working-directory: /home/runner/work/ecommerce-app/ecommerce-app
      run: |
        if [ -d "./dist/ecommerce-app" ]; then echo "Build directory exists."; else echo "Build failed!"; exit 1; fi
        ls ./dist/ecommerce-app

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2FF3A2BCDCB24164AF6BCD4FCB2C7E03 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B612478257EF415792FBCEE83AE332C8 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FA4E1757F0B94C9BB8530F089967366A }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'mywebappr2p'
        slot-name: 'Production'
        package: /home/runner/work/ecommerce-app/ecommerce-app/dist/ecommerce-app

