name: Build and deploy Angular app to Azure Web App - mywebappr2p

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        working-directory: /home/runner/work/ecommerce-app/ecommerce-app
        run: |
          npm install
          npm run build:prod

      - name: Verify build output
        working-directory: /home/runner/work/ecommerce-app/ecommerce-app
        run: |
          if [ -d "./dist/ecommerce-app" ]; then 
            echo "✅ Build directory exists."; 
          else 
            echo "❌ Build failed!"; 
            exit 1; 
          fi
          ls -la ./dist/ecommerce-app

      - name: Zip artifact for deployment
        working-directory: /home/runner/work/ecommerce-app/ecommerce-app
        run: zip -r release.zip dist/ecommerce-app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: /home/runner/work/ecommerce-app/ecommerce-app/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Verify extracted files before deployment
        run: ls -la ./dist/ecommerce-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_43A1C7D178FA4A36AF498B67A52D412F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4CBFCA7394684458A1C2AC63BFB87472 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7383222DED034270BB645AE17EA85368 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mywebappr2p'
          slot-name: 'Production'
          package: ./dist/ecommerce-app/browser
